# Generated by Django 5.1.4 on 2025-01-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_task_project_project_task_projectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
